modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="networkcraft"
version="1.0.0"
displayName="NetworkCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sami0, MCreator"

[[dependencies.networkcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




